### ISSUE TITLE
[Spike] Choose pinning service for IPFS metadata

### ISSUE THREAD

**Issue by 0xKurt** [allo-protocol/micro-grants#22]
We will need to store metadata on ipfs.
Which service do we want to use? 
pinata or moralis to write and cloudflare to read?

**Comment by codenamejason** [comment]
I would suggest pinata

**Comment by thelostone-mc** [comment]
synced with andrea 

IPFS read: cloudfront  
IPFS write: pinata

we can use the same gateways as grants-stack team
