### ISSUE TITLE
Set stewards | who can vote

### ISSUE THREAD

**Issue by codenamejason** [allo-protocol/micro-grants#3]
[Diagram](https://excalidraw.com/#room=88b088e663c38181bf23,etBQUUCt7dE8z2yiA-NGUQ)

<img width="617" alt="Screenshot 2023-11-07 at 12 30 42 PM" src="https://github.com/allo-protocol/micro-grants/assets/9419140/0a462f72-8332-4886-9ad2-76c4e7b7a66b">

**Comment by thelostone-mc** [comment]
Will be set via etherscan
